name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, GitHub! There's a new commit."
