name: OWASP ZAP Scan

on:
  schedule:
    - cron: '15 5 * * 1'  # Schedule to run every 10 minutes

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up permissions 
        run: sudo chmod -R 777 $(pwd)

      - name: Set up Python and send email
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run OWASP ZAP Scan
        run: |
          echo "This is the content of the attachment file" > zap_report.zip
          pwd 
          ls -la
          python ses.py
          ls -lah
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /home/runner/work/workflows/workflows/zap_report.zip

